"""Node labels and relationship types, matching docs/04_KNOWLEDGE_GRAPH.md.
Kept as constants so seed.py, repository.py, and tests never hand-type a
label/relationship string that could silently drift from the schema doc.
"""

LABEL_STUDENT = "Student"
LABEL_SKILL = "Skill"
LABEL_CONCEPT = "Concept"
LABEL_QUESTION = "Question"
LABEL_ASSESSMENT = "Assessment"
LABEL_JOB_ROLE = "JobRole"
LABEL_JOB_DESCRIPTION = "JobDescription"
LABEL_COMPANY = "Company"
LABEL_RESOURCE = "LearningResource"
LABEL_PROJECT = "Project"
LABEL_RESUME_EVIDENCE = "ResumeEvidence"
LABEL_MISSION = "Mission"

REL_HAS_SKILL_STATE = "HAS_SKILL_STATE"
REL_CONTAINS_CONCEPT = "CONTAINS_CONCEPT"
REL_DEPENDS_ON = "DEPENDS_ON"
REL_TESTS = "TESTS"
REL_ANSWERED = "ANSWERED"
REL_FAILED = "FAILED"
REL_DEMONSTRATES = "DEMONSTRATES"
REL_SUPPORTS = "SUPPORTS"
REL_HAS_EVIDENCE = "HAS_EVIDENCE"
REL_REQUIRES = "REQUIRES"
REL_OFFERS = "OFFERS"
REL_MENTIONS = "MENTIONS"
REL_MATCHES = "MATCHES"
REL_TEACHES = "TEACHES"
REL_TARGETS = "TARGETS"
REL_IMPROVES = "IMPROVES"
REL_GENERATED_FROM = "GENERATED_FROM"

ALL_LABELS = [
    LABEL_STUDENT, LABEL_SKILL, LABEL_CONCEPT, LABEL_QUESTION, LABEL_ASSESSMENT,
    LABEL_JOB_ROLE, LABEL_JOB_DESCRIPTION, LABEL_COMPANY, LABEL_RESOURCE,
    LABEL_PROJECT, LABEL_RESUME_EVIDENCE, LABEL_MISSION,
]
