"""Shareable snapshot proof: packages an existing Career Twin snapshot --
scores, confidence, and evidence citations already computed by
app/career_twin/scoring.py -- into a one-page, exportable summary for a
faculty mentor meeting, scholarship application, or recruiter share. Zero
new scoring logic; this is presentation only, resolving each component's
already-stored evidence_ids into readable citations.
"""

import uuid
from dataclasses import dataclass, field

from sqlalchemy import select
from sqlalchemy.orm import Session

from app.models.career_twin import CareerTwinSnapshot
from app.models.skill import SkillEvidence
from app.models.student import StudentProfile

PROOF_DISCLAIMER = (
    "This is a snapshot of evidence-backed readiness at a point in time, generated by CareerPilot AI's "
    "deterministic scoring engine -- not a hiring recommendation, guarantee, or ranking against other students."
)


@dataclass
class EvidenceCitation:
    skill_name: str
    evidence_type: str
    explanation: str
    created_at: str


@dataclass
class ComponentProof:
    component_type: str
    score: float | None
    confidence: float | None
    status: str
    evidence_count: int
    citations: list[EvidenceCitation] = field(default_factory=list)


@dataclass
class SnapshotProof:
    student_name: str
    target_role: str | None
    version: int
    created_at: str
    overall_score: float | None
    overall_confidence: float | None
    formula_version: str
    components: list[ComponentProof] = field(default_factory=list)
    disclaimer: str = PROOF_DISCLAIMER


def build_snapshot_proof(db: Session, student_profile: StudentProfile, snapshot: CareerTwinSnapshot) -> SnapshotProof:
    components: list[ComponentProof] = []
    for component in snapshot.components:
        citations: list[EvidenceCitation] = []
        if component.evidence_ids:
            ids = [uuid.UUID(eid) for eid in component.evidence_ids]
            rows = db.scalars(select(SkillEvidence).where(SkillEvidence.id.in_(ids))).all()
            citations = [
                EvidenceCitation(
                    skill_name=row.skill.name,
                    evidence_type=row.evidence_type,
                    explanation=row.explanation,
                    created_at=row.created_at.isoformat(),
                )
                for row in rows
            ]
        components.append(
            ComponentProof(
                component_type=component.component_type,
                score=float(component.score) if component.score is not None else None,
                confidence=float(component.confidence) if component.confidence is not None else None,
                status=component.status,
                evidence_count=component.evidence_count,
                citations=citations,
            )
        )

    return SnapshotProof(
        student_name=student_profile.full_name,
        target_role=student_profile.primary_target_role.title if student_profile.primary_target_role else None,
        version=snapshot.version,
        created_at=snapshot.created_at.isoformat(),
        overall_score=float(snapshot.overall_score) if snapshot.overall_score is not None else None,
        overall_confidence=float(snapshot.overall_confidence) if snapshot.overall_confidence is not None else None,
        formula_version=snapshot.formula_version,
        components=components,
    )
