"""phase2 assessment engine, resources, care engine, retrieval, evaluation

Revision ID: 2d1305695e6c
Revises: 2e021960668e
Create Date: 2026-08-04 17:14:17.008297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.core.types


# revision identifiers, used by Alembic.
revision: str = '2d1305695e6c'
down_revision: Union[str, Sequence[str], None] = '2e021960668e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_domains',
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assessment_domains', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessment_domains_slug'), ['slug'], unique=True)

    op.create_table('evaluation_runs',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('dataset_name', sa.String(length=100), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('concepts',
    sa.Column('domain_id', app.core.types.GUID(), nullable=False),
    sa.Column('skill_id', app.core.types.GUID(), nullable=True),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['assessment_domains.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain_id', 'slug', name='uq_concept_domain_slug')
    )
    with op.batch_alter_table('concepts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_concepts_domain_id'), ['domain_id'], unique=False)

    op.create_table('evaluation_results',
    sa.Column('run_id', app.core.types.GUID(), nullable=False),
    sa.Column('case_id', sa.String(length=100), nullable=False),
    sa.Column('route_variant', sa.String(length=30), nullable=False),
    sa.Column('route_selected', sa.String(length=30), nullable=False),
    sa.Column('agents_invoked', app.core.types.JSONBType(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('agreement', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('latency_ms', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('token_usage', app.core.types.JSONBType(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('accuracy_label', sa.String(length=20), nullable=True),
    sa.Column('failure', sa.Boolean(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('human_review', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['evaluation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evaluation_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluation_results_run_id'), ['run_id'], unique=False)

    op.create_table('care_executions',
    sa.Column('student_profile_id', app.core.types.GUID(), nullable=True),
    sa.Column('task_type', sa.String(length=60), nullable=False),
    sa.Column('request_summary', sa.Text(), nullable=False),
    sa.Column('input_evidence_ids', app.core.types.JSONBType(), nullable=False),
    sa.Column('routing_factors', app.core.types.JSONBType(), nullable=False),
    sa.Column('route', sa.String(length=30), nullable=False),
    sa.Column('agents_invoked', app.core.types.JSONBType(), nullable=False),
    sa.Column('retrieval_used', sa.Boolean(), nullable=False),
    sa.Column('reflection_used', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('agreement', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('reasoning_summary', sa.Text(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('latency_ms', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('final_status', sa.String(length=20), nullable=False),
    sa.Column('requires_human_review', sa.Boolean(), nullable=False),
    sa.Column('policy_version', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['student_profile_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('care_executions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_care_executions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_care_executions_route'), ['route'], unique=False)
        batch_op.create_index(batch_op.f('ix_care_executions_student_profile_id'), ['student_profile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_care_executions_task_type'), ['task_type'], unique=False)

    op.create_table('concept_dependencies',
    sa.Column('concept_id', app.core.types.GUID(), nullable=False),
    sa.Column('depends_on_id', app.core.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['depends_on_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('concept_id', 'depends_on_id')
    )
    op.create_table('questions',
    sa.Column('domain_id', app.core.types.GUID(), nullable=False),
    sa.Column('concept_id', app.core.types.GUID(), nullable=False),
    sa.Column('question_type', sa.String(length=30), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('options', app.core.types.JSONBType(), nullable=True),
    sa.Column('correct_answer', app.core.types.JSONBType(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('target_role_relevance', app.core.types.JSONBType(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['domain_id'], ['assessment_domains.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questions_concept_id'), ['concept_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_domain_id'), ['domain_id'], unique=False)

    op.create_table('resources',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=150), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('resource_type', sa.String(length=30), nullable=False),
    sa.Column('skill_id', app.core.types.GUID(), nullable=True),
    sa.Column('concept_id', app.core.types.GUID(), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('quality_score', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=False),
    sa.Column('cost', sa.String(length=20), nullable=False),
    sa.Column('prerequisites', app.core.types.JSONBType(), nullable=False),
    sa.Column('source_verified', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('retrieval_documents',
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('source_id', app.core.types.GUID(), nullable=False),
    sa.Column('student_profile_id', app.core.types.GUID(), nullable=True),
    sa.Column('target_role_id', app.core.types.GUID(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('text_hash', sa.String(length=64), nullable=False),
    sa.Column('embedding', app.core.types.JSONBType(), nullable=False),
    sa.Column('embedding_model', sa.String(length=50), nullable=False),
    sa.Column('metadata_json', app.core.types.JSONBType(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['student_profile_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('retrieval_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_retrieval_documents_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_retrieval_documents_source_type'), ['source_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_retrieval_documents_student_profile_id'), ['student_profile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_retrieval_documents_text_hash'), ['text_hash'], unique=False)

    op.create_table('agent_runs',
    sa.Column('care_execution_id', app.core.types.GUID(), nullable=False),
    sa.Column('agent_name', sa.String(length=60), nullable=False),
    sa.Column('prompt_version', sa.String(length=30), nullable=False),
    sa.Column('input_payload', app.core.types.JSONBType(), nullable=False),
    sa.Column('output_payload', app.core.types.JSONBType(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('evidence_citations', app.core.types.JSONBType(), nullable=False),
    sa.Column('inference_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('latency_ms', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['care_execution_id'], ['care_executions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_runs_care_execution_id'), ['care_execution_id'], unique=False)

    op.create_table('assessment_attempts',
    sa.Column('student_profile_id', app.core.types.GUID(), nullable=False),
    sa.Column('domain_id', app.core.types.GUID(), nullable=False),
    sa.Column('target_role_id', app.core.types.GUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['assessment_domains.id'], ),
    sa.ForeignKeyConstraint(['student_profile_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_role_id'], ['target_roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assessment_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessment_attempts_student_profile_id'), ['student_profile_id'], unique=False)

    op.create_table('question_responses',
    sa.Column('attempt_id', app.core.types.GUID(), nullable=False),
    sa.Column('question_id', app.core.types.GUID(), nullable=False),
    sa.Column('concept_id', app.core.types.GUID(), nullable=False),
    sa.Column('response_payload', app.core.types.JSONBType(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('ai_evaluated', sa.Boolean(), nullable=False),
    sa.Column('evaluator_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['assessment_attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('question_responses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_responses_attempt_id'), ['attempt_id'], unique=False)

    with op.batch_alter_table('learning_missions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_concept_id', app.core.types.GUID(), nullable=True))
        # server_default backfills existing rows (Phase 1 demo data, or any
        # prior deployment) before the NOT NULL constraint applies -- omitting
        # it works on SQLite's lenient ALTER TABLE but fails on real Postgres
        # with "column contains null values" when the table already has rows.
        batch_op.add_column(
            sa.Column('tasks', app.core.types.JSONBType(), nullable=False, server_default='[]')
        )
        batch_op.add_column(sa.Column('estimated_minutes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('root_cause', app.core.types.JSONBType(), nullable=True))
        batch_op.add_column(
            sa.Column('resource_ids', app.core.types.JSONBType(), nullable=False, server_default='[]')
        )
        batch_op.add_column(sa.Column('expected_impact_estimate', sa.Numeric(precision=5, scale=4), nullable=True))
        batch_op.add_column(sa.Column('expected_impact_confidence', sa.Numeric(precision=5, scale=4), nullable=True))
        batch_op.add_column(
            sa.Column('outcome_evidence_ids', app.core.types.JSONBType(), nullable=False, server_default='[]')
        )
        batch_op.add_column(sa.Column('actual_observed_change', app.core.types.JSONBType(), nullable=True))
        batch_op.create_foreign_key(
            'fk_learning_missions_target_concept_id', 'concepts', ['target_concept_id'], ['id']
        )

    with op.batch_alter_table('skill_evidence', schema=None) as batch_op:
        batch_op.add_column(sa.Column('concept_id', app.core.types.GUID(), nullable=True))
        batch_op.create_foreign_key('fk_skill_evidence_concept_id', 'concepts', ['concept_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skill_evidence', schema=None) as batch_op:
        batch_op.drop_constraint('fk_skill_evidence_concept_id', type_='foreignkey')
        batch_op.drop_column('concept_id')

    with op.batch_alter_table('learning_missions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_learning_missions_target_concept_id', type_='foreignkey')
        batch_op.drop_column('actual_observed_change')
        batch_op.drop_column('outcome_evidence_ids')
        batch_op.drop_column('expected_impact_confidence')
        batch_op.drop_column('expected_impact_estimate')
        batch_op.drop_column('resource_ids')
        batch_op.drop_column('root_cause')
        batch_op.drop_column('estimated_minutes')
        batch_op.drop_column('tasks')
        batch_op.drop_column('target_concept_id')

    with op.batch_alter_table('question_responses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_responses_attempt_id'))

    op.drop_table('question_responses')
    with op.batch_alter_table('assessment_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessment_attempts_student_profile_id'))

    op.drop_table('assessment_attempts')
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_runs_care_execution_id'))

    op.drop_table('agent_runs')
    with op.batch_alter_table('retrieval_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_retrieval_documents_text_hash'))
        batch_op.drop_index(batch_op.f('ix_retrieval_documents_student_profile_id'))
        batch_op.drop_index(batch_op.f('ix_retrieval_documents_source_type'))
        batch_op.drop_index(batch_op.f('ix_retrieval_documents_source_id'))

    op.drop_table('retrieval_documents')
    op.drop_table('resources')
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questions_domain_id'))
        batch_op.drop_index(batch_op.f('ix_questions_concept_id'))

    op.drop_table('questions')
    op.drop_table('concept_dependencies')
    with op.batch_alter_table('care_executions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_care_executions_task_type'))
        batch_op.drop_index(batch_op.f('ix_care_executions_student_profile_id'))
        batch_op.drop_index(batch_op.f('ix_care_executions_route'))
        batch_op.drop_index(batch_op.f('ix_care_executions_created_at'))

    op.drop_table('care_executions')
    with op.batch_alter_table('evaluation_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluation_results_run_id'))

    op.drop_table('evaluation_results')
    with op.batch_alter_table('concepts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_concepts_domain_id'))

    op.drop_table('concepts')
    op.drop_table('evaluation_runs')
    with op.batch_alter_table('assessment_domains', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessment_domains_slug'))

    op.drop_table('assessment_domains')
    # ### end Alembic commands ###
