"""phase1 initial schema

Revision ID: 788d1325f003
Revises: 
Create Date: 2026-08-04 10:41:49.772214

"""
from collections.abc import Sequence

import sqlalchemy as sa

import app.core.types
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '788d1325f003'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('skills',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('aliases', app.core.types.JSONBType(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skills_name'), ['name'], unique=True)

    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('refresh_tokens',
    sa.Column('user_id', app.core.types.GUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash', name='uq_refresh_token_hash')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_token_hash'), ['token_hash'], unique=False)

    op.create_table('student_profiles',
    sa.Column('user_id', app.core.types.GUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.Column('consent_settings', app.core.types.JSONBType(), nullable=False),
    sa.Column('primary_target_role_id', app.core.types.GUID(), nullable=True),
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_roles',
    sa.Column('user_id', app.core.types.GUID(), nullable=False),
    sa.Column('role_id', app.core.types.GUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('audit_events',
    sa.Column('user_id', app.core.types.GUID(), nullable=True),
    sa.Column('student_profile_id', app.core.types.GUID(), nullable=True),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('payload', app.core.types.JSONBType(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['student_profile_id'], ['student_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_student_profile_id'), ['student_profile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_user_id'), ['user_id'], unique=False)

    op.create_table('career_goals',
    sa.Column('student_profile_id', app.core.types.GUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('timeline_months', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_profile_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('career_twin_snapshots',
    sa.Column('student_profile_id', app.core.types.GUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('overall_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('formula_version', sa.String(length=30), nullable=False),
    sa.Column('change_summary', sa.Text(), nullable=False),
    sa.Column('score_delta', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('previous_snapshot_id', app.core.types.GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['previous_snapshot_id'], ['career_twin_snapshots.id'], ),
    sa.ForeignKeyConstraint(['student_profile_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_profile_id', 'version', name='uq_twin_version')
    )
    with op.batch_alter_table('career_twin_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_career_twin_snapshots_student_profile_id'), ['student_profile_id'], unique=False)

    op.create_table('decision_traces',
    sa.Column('student_profile_id', app.core.types.GUID(), nullable=True),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('route', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('agreement', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('evidence_ids', app.core.types.JSONBType(), nullable=False),
    sa.Column('agents_invoked', app.core.types.JSONBType(), nullable=False),
    sa.Column('model_versions', app.core.types.JSONBType(), nullable=False),
    sa.Column('reasoning_summary', sa.Text(), nullable=False),
    sa.Column('requires_human_review', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['student_profile_id'], ['student_profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('decision_traces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_decision_traces_student_profile_id'), ['student_profile_id'], unique=False)

    op.create_table('job_descriptions',
    sa.Column('student_profile_id', app.core.types.GUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['student_profile_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_descriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_descriptions_student_profile_id'), ['student_profile_id'], unique=False)

    op.create_table('learning_missions',
    sa.Column('student_profile_id', app.core.types.GUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('target_skill_id', app.core.types.GUID(), nullable=True),
    sa.Column('source_component', sa.String(length=40), nullable=False),
    sa.Column('priority_rank', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('evidence_ids', app.core.types.JSONBType(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['student_profile_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('learning_missions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learning_missions_student_profile_id'), ['student_profile_id'], unique=False)

    op.create_table('resumes',
    sa.Column('student_profile_id', app.core.types.GUID(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('parsing_status', sa.String(length=20), nullable=False),
    sa.Column('parsing_error', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('parsed_at', sa.DateTime(), nullable=True),
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['student_profile_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resumes_student_profile_id'), ['student_profile_id'], unique=False)

    op.create_table('skill_evidence',
    sa.Column('student_profile_id', app.core.types.GUID(), nullable=False),
    sa.Column('skill_id', app.core.types.GUID(), nullable=False),
    sa.Column('evidence_type', sa.String(length=50), nullable=False),
    sa.Column('source_object_type', sa.String(length=50), nullable=False),
    sa.Column('source_object_id', app.core.types.GUID(), nullable=True),
    sa.Column('raw_score', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('normalized_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('weight', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_profile_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('skill_evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skill_evidence_student_profile_id'), ['student_profile_id'], unique=False)

    op.create_table('student_skills',
    sa.Column('student_profile_id', app.core.types.GUID(), nullable=False),
    sa.Column('skill_id', app.core.types.GUID(), nullable=False),
    sa.Column('self_rating', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_profile_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_profile_id', 'skill_id', name='uq_student_skill')
    )
    with op.batch_alter_table('student_skills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_skills_student_profile_id'), ['student_profile_id'], unique=False)

    op.create_table('target_roles',
    sa.Column('student_profile_id', app.core.types.GUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('seniority', sa.String(length=50), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_profile_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.create_foreign_key(
            'fk_student_profiles_primary_target_role_id',
            'target_roles',
            ['primary_target_role_id'],
            ['id'],
            ondelete='SET NULL',
        )

    op.create_table('job_requirements',
    sa.Column('job_description_id', app.core.types.GUID(), nullable=False),
    sa.Column('requirement_type', sa.String(length=30), nullable=False),
    sa.Column('skill_id', app.core.types.GUID(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['job_description_id'], ['job_descriptions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('readiness_components',
    sa.Column('snapshot_id', app.core.types.GUID(), nullable=False),
    sa.Column('component_type', sa.String(length=40), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('evidence_ids', app.core.types.JSONBType(), nullable=False),
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['career_twin_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('readiness_components', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_readiness_components_snapshot_id'), ['snapshot_id'], unique=False)

    op.create_table('resume_sections',
    sa.Column('resume_id', app.core.types.GUID(), nullable=False),
    sa.Column('section_type', sa.String(length=30), nullable=False),
    sa.Column('heading', sa.String(length=255), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resume_skills',
    sa.Column('resume_id', app.core.types.GUID(), nullable=False),
    sa.Column('skill_id', app.core.types.GUID(), nullable=False),
    sa.Column('evidence_snippet', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resume_id', 'skill_id', name='uq_resume_skill')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resume_skills')
    op.drop_table('resume_sections')
    with op.batch_alter_table('readiness_components', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_readiness_components_snapshot_id'))

    op.drop_table('readiness_components')
    op.drop_table('job_requirements')
    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.drop_constraint('fk_student_profiles_primary_target_role_id', type_='foreignkey')

    op.drop_table('target_roles')
    with op.batch_alter_table('student_skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_skills_student_profile_id'))

    op.drop_table('student_skills')
    with op.batch_alter_table('skill_evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skill_evidence_student_profile_id'))

    op.drop_table('skill_evidence')
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resumes_student_profile_id'))

    op.drop_table('resumes')
    with op.batch_alter_table('learning_missions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learning_missions_student_profile_id'))

    op.drop_table('learning_missions')
    with op.batch_alter_table('job_descriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_descriptions_student_profile_id'))

    op.drop_table('job_descriptions')
    with op.batch_alter_table('decision_traces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_decision_traces_student_profile_id'))

    op.drop_table('decision_traces')
    with op.batch_alter_table('career_twin_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_career_twin_snapshots_student_profile_id'))

    op.drop_table('career_twin_snapshots')
    op.drop_table('career_goals')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_student_profile_id'))

    op.drop_table('audit_events')
    op.drop_table('user_roles')
    op.drop_table('student_profiles')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_token_hash'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skills_name'))

    op.drop_table('skills')
    op.drop_table('roles')
    # ### end Alembic commands ###
