"""career twin v2 small sample safeguard

Revision ID: 7ba5f89c3126
Revises: ccca34eecf1f
Create Date: 2026-08-05 00:54:00.497696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ba5f89c3126'
down_revision: Union[str, Sequence[str], None] = 'ccca34eecf1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default backfills existing rows before the NOT NULL constraint
    # applies -- required against a non-empty Postgres table (see the
    # learning_missions migration 2d1305695e6c for the same pitfall).
    with op.batch_alter_table('readiness_components', schema=None) as batch_op:
        batch_op.add_column(sa.Column('evidence_diversity', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('is_low_sample', sa.Boolean(), nullable=False, server_default=sa.false()))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('readiness_components', schema=None) as batch_op:
        batch_op.drop_column('is_low_sample')
        batch_op.drop_column('evidence_diversity')

    # ### end Alembic commands ###
