"""interview arena schema

Revision ID: ccca34eecf1f
Revises: 298c98dafbbb
Create Date: 2026-08-04 21:29:22.277153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.core.types


# revision identifiers, used by Alembic.
revision: str = 'ccca34eecf1f'
down_revision: Union[str, Sequence[str], None] = '298c98dafbbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_sessions',
    sa.Column('student_profile_id', app.core.types.GUID(), nullable=False),
    sa.Column('mode', sa.String(length=30), nullable=False),
    sa.Column('target_role_id', app.core.types.GUID(), nullable=True),
    sa.Column('job_description_id', app.core.types.GUID(), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('overall_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('overall_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['job_description_id'], ['job_descriptions.id'], ),
    sa.ForeignKeyConstraint(['student_profile_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_role_id'], ['target_roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interview_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interview_sessions_student_profile_id'), ['student_profile_id'], unique=False)

    op.create_table('interview_questions',
    sa.Column('session_id', app.core.types.GUID(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=30), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('question_source', sa.String(length=30), nullable=False),
    sa.Column('concept_id', app.core.types.GUID(), nullable=True),
    sa.Column('expected_keywords', app.core.types.JSONBType(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interview_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interview_questions_session_id'), ['session_id'], unique=False)

    op.create_table('interview_answers',
    sa.Column('question_id', app.core.types.GUID(), nullable=False),
    sa.Column('audio_storage_path', sa.String(length=500), nullable=True),
    sa.Column('audio_mime_type', sa.String(length=60), nullable=True),
    sa.Column('audio_duration_seconds', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=False),
    sa.Column('transcript_source', sa.String(length=30), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['interview_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interview_answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interview_answers_question_id'), ['question_id'], unique=True)

    op.create_table('interview_evaluations',
    sa.Column('answer_id', app.core.types.GUID(), nullable=False),
    sa.Column('care_execution_id', app.core.types.GUID(), nullable=True),
    sa.Column('dimension_scores', app.core.types.JSONBType(), nullable=False),
    sa.Column('overall_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('agreement', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('strengths', app.core.types.JSONBType(), nullable=False),
    sa.Column('improvements', app.core.types.JSONBType(), nullable=False),
    sa.Column('evidence_checks', app.core.types.JSONBType(), nullable=False),
    sa.Column('communication_metrics', app.core.types.JSONBType(), nullable=False),
    sa.Column('timeline_markers', app.core.types.JSONBType(), nullable=False),
    sa.Column('better_answer_framework', sa.Text(), nullable=False),
    sa.Column('requires_human_review', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['interview_answers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['care_execution_id'], ['care_executions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interview_evaluations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interview_evaluations_answer_id'), ['answer_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_evaluations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interview_evaluations_answer_id'))

    op.drop_table('interview_evaluations')
    with op.batch_alter_table('interview_answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interview_answers_question_id'))

    op.drop_table('interview_answers')
    with op.batch_alter_table('interview_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interview_questions_session_id'))

    op.drop_table('interview_questions')
    with op.batch_alter_table('interview_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interview_sessions_student_profile_id'))

    op.drop_table('interview_sessions')
    # ### end Alembic commands ###
