"""career twin freshness columns

Revision ID: eafa4695568e
Revises: 6181bfa011a8
Create Date: 2026-08-06 10:19:06.174055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eafa4695568e'
down_revision: Union[str, Sequence[str], None] = '6181bfa011a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default backfills existing rows (pre-existing snapshots predate
    # the freshness safeguard, so "not stale" is the correct historical
    # default -- their evidence was, in fact, all fresh at scoring time).
    op.add_column(
        'readiness_components',
        sa.Column('stale_evidence_fraction', sa.Numeric(precision=5, scale=4), nullable=False, server_default='0'),
    )
    op.add_column(
        'readiness_components',
        sa.Column('is_stale_evidence', sa.Boolean(), nullable=False, server_default=sa.false()),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('readiness_components', 'is_stale_evidence')
    op.drop_column('readiness_components', 'stale_evidence_fraction')
    # ### end Alembic commands ###
