"""student profile dob college year branch

Revision ID: ebab97440c22
Revises: edad7e0b3711
Create Date: 2026-08-06 16:38:12.115498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebab97440c22'
down_revision: Union[str, Sequence[str], None] = 'edad7e0b3711'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_profiles', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('student_profiles', sa.Column('college_year', sa.String(length=50), nullable=True))
    op.add_column('student_profiles', sa.Column('branch', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_profiles', 'branch')
    op.drop_column('student_profiles', 'college_year')
    op.drop_column('student_profiles', 'date_of_birth')
    # ### end Alembic commands ###
