"""Company Job Catalog reference data: real-shaped (not live-scraped) job
openings across six sectors, used by Job Match's dream-company search,
readiness scoring, and tracked-job list. Loaded via an Alembic data
migration, exactly like assessment_taxonomy.py and skills_taxonomy.py.

Every listing's required skills reference names from
app/seed/skills_taxonomy.py's SKILLS catalog, so readiness scoring reuses
the exact same resume-evidence weighting as everywhere else in the app --
no separate scoring system, no invented numbers.

package_min/package_max are in LPA (lakhs per annum, INR) -- illustrative,
representative ranges for entry-level/new-grad hiring, not live market data.
"""

from app.models.job_catalog import (
    SECTOR_CONSULTING,
    SECTOR_FAANG,
    SECTOR_FINANCE,
    SECTOR_GOVERNMENT,
    SECTOR_RESEARCH,
    SECTOR_STARTUP,
)

# (company, title, sector, seniority, package_min, package_max, description,
#  emphasis_domains, required_skills, optional_skills)
LISTINGS: list[dict] = [
    # ---- FAANG / Big Tech ----
    {
        "company": "Google", "title": "Software Engineer, New Grad", "sector": SECTOR_FAANG,
        "seniority": "entry_level", "package_min": 30, "package_max": 45,
        "description": "Build and scale core infrastructure and product features used by billions of users.",
        "emphasis_domains": ["dsa", "python", "java"],
        "required_skills": ["Data Structures", "Algorithms", "System Design", "Python"],
        "optional_skills": ["Java", "Go"],
    },
    {
        "company": "Meta", "title": "Software Engineer, University Grad", "sector": SECTOR_FAANG,
        "seniority": "entry_level", "package_min": 28, "package_max": 42,
        "description": "Ship product and infrastructure across Meta's family of apps at massive scale.",
        "emphasis_domains": ["dsa", "javascript", "oop"],
        "required_skills": ["Data Structures", "Algorithms", "React", "JavaScript"],
        "optional_skills": ["System Design"],
    },
    {
        "company": "Amazon", "title": "SDE I", "sector": SECTOR_FAANG,
        "seniority": "entry_level", "package_min": 24, "package_max": 36,
        "description": "Own services end-to-end in one of the world's largest distributed systems.",
        "emphasis_domains": ["dsa", "java", "sql"],
        "required_skills": ["Data Structures", "Algorithms", "Java", "AWS"],
        "optional_skills": ["SQL"],
    },
    {
        "company": "Amazon", "title": "Data Engineer I", "sector": SECTOR_FAANG,
        "seniority": "entry_level", "package_min": 22, "package_max": 32,
        "description": "Build data pipelines and warehousing solutions powering Amazon's analytics.",
        "emphasis_domains": ["sql", "python"],
        "required_skills": ["SQL", "Python", "AWS", "Data Analysis"],
        "optional_skills": ["Pandas"],
    },
    {
        "company": "Microsoft", "title": "Software Engineer", "sector": SECTOR_FAANG,
        "seniority": "entry_level", "package_min": 26, "package_max": 38,
        "description": "Build products across Azure, Windows, or Microsoft 365 with a huge engineering org.",
        "emphasis_domains": ["dsa", "oop", "java"],
        "required_skills": ["Data Structures", "Algorithms", "C#", "System Design"],
        "optional_skills": ["Azure"],
    },
    {
        "company": "Microsoft", "title": "Cloud Solutions Engineer", "sector": SECTOR_FAANG,
        "seniority": "entry_level", "package_min": 20, "package_max": 30,
        "description": "Help enterprise customers design and deploy solutions on Microsoft Azure.",
        "emphasis_domains": ["sql", "python"],
        "required_skills": ["Azure", "SQL", "Python"],
        "optional_skills": ["Docker"],
    },
    {
        "company": "Apple", "title": "Software Engineer, iOS", "sector": SECTOR_FAANG,
        "seniority": "entry_level", "package_min": 27, "package_max": 40,
        "description": "Craft the software experience behind Apple's consumer devices.",
        "emphasis_domains": ["oop", "dsa"],
        "required_skills": ["Swift", "Data Structures", "Algorithms"],
        "optional_skills": ["System Design"],
    },
    {
        "company": "Netflix", "title": "Backend Engineer", "sector": SECTOR_FAANG,
        "seniority": "entry_level", "package_min": 30, "package_max": 44,
        "description": "Build the streaming platform's backend services at global scale.",
        "emphasis_domains": ["java", "dsa", "sql"],
        "required_skills": ["Java", "System Design", "AWS", "SQL"],
        "optional_skills": ["Kubernetes"],
    },
    {
        "company": "Adobe", "title": "Software Development Engineer", "sector": SECTOR_FAANG,
        "seniority": "entry_level", "package_min": 18, "package_max": 28,
        "description": "Build creative-cloud and document-cloud products used by millions of creators.",
        "emphasis_domains": ["oop", "dsa"],
        "required_skills": ["Data Structures", "Algorithms", "Java"],
        "optional_skills": ["React"],
    },
    {
        "company": "NVIDIA", "title": "Software Engineer, Platform", "sector": SECTOR_FAANG,
        "seniority": "entry_level", "package_min": 22, "package_max": 34,
        "description": "Build platform software for GPU-accelerated computing.",
        "emphasis_domains": ["dsa", "python"],
        "required_skills": ["C++", "Data Structures", "Algorithms", "Python"],
        "optional_skills": ["Machine Learning"],
    },

    # ---- Startup ----
    {
        "company": "Stripe", "title": "Backend Engineer", "sector": SECTOR_STARTUP,
        "seniority": "entry_level", "package_min": 18, "package_max": 30,
        "description": "Build the APIs and infrastructure that power internet payments.",
        "emphasis_domains": ["python", "sql"],
        "required_skills": ["Python", "SQL", "REST APIs"],
        "optional_skills": ["PostgreSQL"],
    },
    {
        "company": "Notion", "title": "Full Stack Engineer", "sector": SECTOR_STARTUP,
        "seniority": "entry_level", "package_min": 15, "package_max": 26,
        "description": "Build the collaborative workspace product end to end, frontend to backend.",
        "emphasis_domains": ["javascript", "oop"],
        "required_skills": ["React", "TypeScript", "Node.js"],
        "optional_skills": ["GraphQL"],
    },
    {
        "company": "Figma", "title": "Frontend Engineer", "sector": SECTOR_STARTUP,
        "seniority": "entry_level", "package_min": 16, "package_max": 27,
        "description": "Build the design-tool interface used by millions of designers and engineers.",
        "emphasis_domains": ["javascript"],
        "required_skills": ["JavaScript", "React", "CSS"],
        "optional_skills": ["TypeScript"],
    },
    {
        "company": "Razorpay", "title": "Software Engineer", "sector": SECTOR_STARTUP,
        "seniority": "entry_level", "package_min": 10, "package_max": 20,
        "description": "Build payment infrastructure for businesses across India.",
        "emphasis_domains": ["java", "sql"],
        "required_skills": ["Java", "SQL", "REST APIs"],
        "optional_skills": ["Docker"],
    },
    {
        "company": "Zerodha", "title": "Backend Developer", "sector": SECTOR_STARTUP,
        "seniority": "entry_level", "package_min": 8, "package_max": 18,
        "description": "Build low-latency trading and broking systems used by millions of investors.",
        "emphasis_domains": ["python", "sql"],
        "required_skills": ["Python", "SQL", "Data Structures"],
        "optional_skills": ["Redis"],
    },
    {
        "company": "Postman", "title": "Software Engineer", "sector": SECTOR_STARTUP,
        "seniority": "entry_level", "package_min": 12, "package_max": 22,
        "description": "Build the API platform used by millions of developers worldwide.",
        "emphasis_domains": ["javascript", "oop"],
        "required_skills": ["JavaScript", "Node.js", "REST APIs"],
        "optional_skills": ["MongoDB"],
    },
    {
        "company": "Freshworks", "title": "SDE I", "sector": SECTOR_STARTUP,
        "seniority": "entry_level", "package_min": 9, "package_max": 16,
        "description": "Build customer-engagement SaaS products used by businesses globally.",
        "emphasis_domains": ["java", "sql"],
        "required_skills": ["Java", "SQL", "REST APIs"],
        "optional_skills": ["React"],
    },
    {
        "company": "CRED", "title": "Backend Engineer", "sector": SECTOR_STARTUP,
        "seniority": "entry_level", "package_min": 15, "package_max": 28,
        "description": "Build fintech products for India's most creditworthy customers.",
        "emphasis_domains": ["java", "sql"],
        "required_skills": ["Java", "SQL", "System Design"],
        "optional_skills": ["Kubernetes"],
    },
    {
        "company": "Zomato", "title": "Software Engineer", "sector": SECTOR_STARTUP,
        "seniority": "entry_level", "package_min": 10, "package_max": 20,
        "description": "Build the platform connecting millions of diners and restaurants.",
        "emphasis_domains": ["python", "dsa"],
        "required_skills": ["Python", "Data Structures", "SQL"],
        "optional_skills": ["Django"],
    },
    {
        "company": "Swiggy", "title": "SDE I", "sector": SECTOR_STARTUP,
        "seniority": "entry_level", "package_min": 10, "package_max": 20,
        "description": "Build logistics and marketplace systems for on-demand delivery at scale.",
        "emphasis_domains": ["java", "dsa"],
        "required_skills": ["Java", "Data Structures", "Algorithms"],
        "optional_skills": ["AWS"],
    },

    # ---- Research ----
    {
        "company": "ISRO", "title": "Scientist/Engineer 'SC'", "sector": SECTOR_RESEARCH,
        "seniority": "entry_level", "package_min": 6, "package_max": 12,
        "description": "Contribute to spacecraft software systems and mission-critical engineering.",
        "emphasis_domains": ["python", "dsa"],
        "required_skills": ["Python", "C++", "Data Structures"],
        "optional_skills": ["Algorithms"],
    },
    {
        "company": "DRDO", "title": "Scientist 'B'", "sector": SECTOR_RESEARCH,
        "seniority": "entry_level", "package_min": 6, "package_max": 11,
        "description": "Research and develop defense technology systems.",
        "emphasis_domains": ["python", "oop"],
        "required_skills": ["Python", "C++", "Data Structures"],
        "optional_skills": ["Machine Learning"],
    },
    {
        "company": "CSIR", "title": "Research Associate (CS)", "sector": SECTOR_RESEARCH,
        "seniority": "entry_level", "package_min": 6, "package_max": 10,
        "description": "Conduct applied research across CSIR's national laboratories.",
        "emphasis_domains": ["python"],
        "required_skills": ["Python", "Data Analysis"],
        "optional_skills": ["Machine Learning"],
    },
    {
        "company": "OpenAI", "title": "Research Engineer", "sector": SECTOR_RESEARCH,
        "seniority": "entry_level", "package_min": 35, "package_max": 55,
        "description": "Build and scale the infrastructure and experiments behind frontier AI models.",
        "emphasis_domains": ["python", "dsa"],
        "required_skills": ["Python", "Machine Learning", "Deep Learning", "PyTorch"],
        "optional_skills": ["Data Structures"],
    },
    {
        "company": "DeepMind", "title": "Research Engineer", "sector": SECTOR_RESEARCH,
        "seniority": "entry_level", "package_min": 35, "package_max": 55,
        "description": "Build the systems and experiments behind cutting-edge AI research.",
        "emphasis_domains": ["python", "dsa"],
        "required_skills": ["Python", "Machine Learning", "TensorFlow", "Algorithms"],
        "optional_skills": ["Deep Learning"],
    },
    {
        "company": "Microsoft Research", "title": "Research Assistant", "sector": SECTOR_RESEARCH,
        "seniority": "entry_level", "package_min": 14, "package_max": 24,
        "description": "Support ongoing research projects across systems, AI, and HCI.",
        "emphasis_domains": ["python"],
        "required_skills": ["Python", "Machine Learning", "Data Analysis"],
        "optional_skills": ["Natural Language Processing"],
    },
    {
        "company": "IIT Bombay", "title": "Research Assistant, ML Lab", "sector": SECTOR_RESEARCH,
        "seniority": "entry_level", "package_min": 5, "package_max": 9,
        "description": "Support faculty-led machine learning research projects.",
        "emphasis_domains": ["python"],
        "required_skills": ["Python", "Machine Learning"],
        "optional_skills": ["NumPy"],
    },
    {
        "company": "TCS Research", "title": "Researcher", "sector": SECTOR_RESEARCH,
        "seniority": "entry_level", "package_min": 8, "package_max": 14,
        "description": "Applied research across AI, data, and enterprise systems for TCS's global clients.",
        "emphasis_domains": ["python", "sql"],
        "required_skills": ["Python", "SQL", "Data Analysis"],
        "optional_skills": ["Machine Learning"],
    },
    {
        "company": "NVIDIA Research", "title": "Research Scientist, Intern-to-Full-Time", "sector": SECTOR_RESEARCH,
        "seniority": "entry_level", "package_min": 25, "package_max": 40,
        "description": "Research next-generation GPU-accelerated AI and graphics systems.",
        "emphasis_domains": ["python", "dsa"],
        "required_skills": ["Python", "Machine Learning", "Deep Learning"],
        "optional_skills": ["Computer Vision"],
    },
    {
        "company": "Adobe Research", "title": "Research Engineer", "sector": SECTOR_RESEARCH,
        "seniority": "entry_level", "package_min": 18, "package_max": 30,
        "description": "Research computer vision and generative AI for creative tools.",
        "emphasis_domains": ["python"],
        "required_skills": ["Python", "Computer Vision", "Machine Learning"],
        "optional_skills": ["PyTorch"],
    },

    # ---- Government / PSU ----
    {
        "company": "National Informatics Centre", "title": "Scientific Officer", "sector": SECTOR_GOVERNMENT,
        "seniority": "entry_level", "package_min": 7, "package_max": 12,
        "description": "Build and maintain digital infrastructure for Indian government services.",
        "emphasis_domains": ["sql", "java"],
        "required_skills": ["SQL", "Java", "System Design"],
        "optional_skills": ["Python"],
    },
    {
        "company": "UIDAI", "title": "Technical Officer", "sector": SECTOR_GOVERNMENT,
        "seniority": "entry_level", "package_min": 8, "package_max": 13,
        "description": "Support the technology backbone of India's national identity platform, Aadhaar.",
        "emphasis_domains": ["sql", "java"],
        "required_skills": ["SQL", "Java", "System Design"],
        "optional_skills": ["Linux"],
    },
    {
        "company": "CRIS (Indian Railways)", "title": "Software Engineer", "sector": SECTOR_GOVERNMENT,
        "seniority": "entry_level", "package_min": 6, "package_max": 11,
        "description": "Build reservation, freight, and operations systems for Indian Railways.",
        "emphasis_domains": ["sql", "java"],
        "required_skills": ["SQL", "Java"],
        "optional_skills": ["System Design"],
    },
    {
        "company": "Bharat Electronics Limited", "title": "Engineer (CS)", "sector": SECTOR_GOVERNMENT,
        "seniority": "entry_level", "package_min": 7, "package_max": 12,
        "description": "Develop embedded and defense electronics software systems.",
        "emphasis_domains": ["oop", "python"],
        "required_skills": ["C++", "Python", "Data Structures"],
        "optional_skills": ["Linux"],
    },
    {
        "company": "State Bank of India", "title": "Systems Officer (IT)", "sector": SECTOR_GOVERNMENT,
        "seniority": "entry_level", "package_min": 8, "package_max": 14,
        "description": "Manage and build core banking technology systems for India's largest bank.",
        "emphasis_domains": ["sql", "java"],
        "required_skills": ["SQL", "Java", "System Design"],
        "optional_skills": ["Linux"],
    },
    {
        "company": "Reserve Bank of India", "title": "Grade B Officer (DEPR-IT)", "sector": SECTOR_GOVERNMENT,
        "seniority": "entry_level", "package_min": 10, "package_max": 16,
        "description": "Support India's central bank's technology and data-analysis functions.",
        "emphasis_domains": ["sql", "python"],
        "required_skills": ["SQL", "Python", "Data Analysis"],
        "optional_skills": ["System Design"],
    },
    {
        "company": "ISRO", "title": "IT Systems Engineer", "sector": SECTOR_GOVERNMENT,
        "seniority": "entry_level", "package_min": 7, "package_max": 12,
        "description": "Maintain the ground-station and enterprise IT systems supporting Indian space missions.",
        "emphasis_domains": ["sql", "python"],
        "required_skills": ["SQL", "Python", "Linux"],
        "optional_skills": ["System Design"],
    },
    {
        "company": "Directorate General of Civil Aviation", "title": "IT Officer", "sector": SECTOR_GOVERNMENT,
        "seniority": "entry_level", "package_min": 7, "package_max": 11,
        "description": "Support aviation-safety digital systems and infrastructure.",
        "emphasis_domains": ["sql"],
        "required_skills": ["SQL", "System Design"],
        "optional_skills": ["Java"],
    },
    {
        "company": "Income Tax Department", "title": "Systems Officer", "sector": SECTOR_GOVERNMENT,
        "seniority": "entry_level", "package_min": 7, "package_max": 12,
        "description": "Build and maintain nationwide tax-filing and compliance systems.",
        "emphasis_domains": ["sql", "java"],
        "required_skills": ["SQL", "Java"],
        "optional_skills": ["Data Analysis"],
    },
    {
        "company": "BHEL", "title": "Engineer Trainee (IT)", "sector": SECTOR_GOVERNMENT,
        "seniority": "entry_level", "package_min": 6, "package_max": 10,
        "description": "Support enterprise IT systems for India's largest power-equipment manufacturer.",
        "emphasis_domains": ["sql", "java"],
        "required_skills": ["SQL", "Java"],
        "optional_skills": ["System Design"],
    },

    # ---- Consulting ----
    {
        "company": "Deloitte", "title": "Technology Consultant", "sector": SECTOR_CONSULTING,
        "seniority": "entry_level", "package_min": 8, "package_max": 15,
        "description": "Advise enterprise clients on technology strategy and implementation.",
        "emphasis_domains": ["sql", "python"],
        "required_skills": ["SQL", "Python", "Communication"],
        "optional_skills": ["Data Analysis"],
    },
    {
        "company": "McKinsey & Company", "title": "Business Technology Analyst", "sector": SECTOR_CONSULTING,
        "seniority": "entry_level", "package_min": 15, "package_max": 26,
        "description": "Combine technical and business skills to solve clients' toughest problems.",
        "emphasis_domains": ["python", "sql"],
        "required_skills": ["Python", "SQL", "Communication", "Problem Solving"],
        "optional_skills": ["Data Analysis"],
    },
    {
        "company": "Accenture", "title": "Software Engineer", "sector": SECTOR_CONSULTING,
        "seniority": "entry_level", "package_min": 6, "package_max": 12,
        "description": "Deliver technology solutions for Accenture's global enterprise clients.",
        "emphasis_domains": ["java", "sql"],
        "required_skills": ["Java", "SQL"],
        "optional_skills": ["React"],
    },
    {
        "company": "BCG Platinion", "title": "Technology Consultant", "sector": SECTOR_CONSULTING,
        "seniority": "entry_level", "package_min": 14, "package_max": 24,
        "description": "Architect and deliver technology transformation programs for BCG's clients.",
        "emphasis_domains": ["sql", "python"],
        "required_skills": ["SQL", "Python", "System Design", "Communication"],
        "optional_skills": ["Project Management"],
    },
    {
        "company": "EY", "title": "Technology Consultant", "sector": SECTOR_CONSULTING,
        "seniority": "entry_level", "package_min": 7, "package_max": 13,
        "description": "Advise clients on digital transformation and technology risk.",
        "emphasis_domains": ["sql", "python"],
        "required_skills": ["SQL", "Python", "Communication"],
        "optional_skills": ["Data Analysis"],
    },
    {
        "company": "PwC", "title": "Associate Consultant, Technology", "sector": SECTOR_CONSULTING,
        "seniority": "entry_level", "package_min": 7, "package_max": 13,
        "description": "Deliver technology-enabled business solutions for PwC's clients.",
        "emphasis_domains": ["sql", "java"],
        "required_skills": ["SQL", "Java", "Communication"],
        "optional_skills": ["Agile/Scrum"],
    },
    {
        "company": "Capgemini", "title": "Software Engineer", "sector": SECTOR_CONSULTING,
        "seniority": "entry_level", "package_min": 5, "package_max": 9,
        "description": "Build and maintain software solutions for global enterprise clients.",
        "emphasis_domains": ["java", "sql"],
        "required_skills": ["Java", "SQL"],
        "optional_skills": ["Python"],
    },
    {
        "company": "Cognizant", "title": "Programmer Analyst", "sector": SECTOR_CONSULTING,
        "seniority": "entry_level", "package_min": 4, "package_max": 8,
        "description": "Develop and support enterprise applications for Cognizant's global clients.",
        "emphasis_domains": ["java", "sql"],
        "required_skills": ["Java", "SQL"],
        "optional_skills": ["Testing"],
    },
    {
        "company": "Infosys", "title": "Systems Engineer", "sector": SECTOR_CONSULTING,
        "seniority": "entry_level", "package_min": 4, "package_max": 8,
        "description": "Build enterprise software solutions across Infosys's global client base.",
        "emphasis_domains": ["java", "sql"],
        "required_skills": ["Java", "SQL"],
        "optional_skills": ["Python"],
    },
    {
        "company": "Tata Consultancy Services", "title": "Assistant System Engineer", "sector": SECTOR_CONSULTING,
        "seniority": "entry_level", "package_min": 3.5, "package_max": 7,
        "description": "Deliver IT services and enterprise solutions across TCS's global client base.",
        "emphasis_domains": ["java", "sql"],
        "required_skills": ["Java", "SQL"],
        "optional_skills": ["Communication"],
    },

    # ---- Finance ----
    {
        "company": "Goldman Sachs", "title": "Software Engineer", "sector": SECTOR_FINANCE,
        "seniority": "entry_level", "package_min": 20, "package_max": 34,
        "description": "Build trading, risk, and platform engineering systems for global markets.",
        "emphasis_domains": ["java", "dsa", "sql"],
        "required_skills": ["Java", "Data Structures", "SQL", "System Design"],
        "optional_skills": ["Python"],
    },
    {
        "company": "JPMorgan Chase", "title": "Software Engineer Program", "sector": SECTOR_FINANCE,
        "seniority": "entry_level", "package_min": 18, "package_max": 30,
        "description": "Build technology powering global banking and markets infrastructure.",
        "emphasis_domains": ["java", "sql"],
        "required_skills": ["Java", "SQL", "Data Structures"],
        "optional_skills": ["Python"],
    },
    {
        "company": "Morgan Stanley", "title": "Technology Analyst", "sector": SECTOR_FINANCE,
        "seniority": "entry_level", "package_min": 17, "package_max": 28,
        "description": "Build software for trading, wealth management, and risk platforms.",
        "emphasis_domains": ["java", "python"],
        "required_skills": ["Java", "Python", "SQL"],
        "optional_skills": ["System Design"],
    },
    {
        "company": "HSBC", "title": "Software Developer", "sector": SECTOR_FINANCE,
        "seniority": "entry_level", "package_min": 10, "package_max": 18,
        "description": "Build core banking and digital platform software for a global bank.",
        "emphasis_domains": ["java", "sql"],
        "required_skills": ["Java", "SQL"],
        "optional_skills": ["React"],
    },
    {
        "company": "Visa", "title": "Software Engineer", "sector": SECTOR_FINANCE,
        "seniority": "entry_level", "package_min": 16, "package_max": 26,
        "description": "Build the payment network processing tens of billions of transactions a year.",
        "emphasis_domains": ["java", "dsa"],
        "required_skills": ["Java", "Data Structures", "System Design"],
        "optional_skills": ["SQL"],
    },
    {
        "company": "Mastercard", "title": "Software Engineer", "sector": SECTOR_FINANCE,
        "seniority": "entry_level", "package_min": 15, "package_max": 25,
        "description": "Build secure, scalable payment technology used worldwide.",
        "emphasis_domains": ["java", "sql"],
        "required_skills": ["Java", "SQL", "System Design"],
        "optional_skills": ["AWS"],
    },
    {
        "company": "American Express", "title": "Technology Analyst", "sector": SECTOR_FINANCE,
        "seniority": "entry_level", "package_min": 12, "package_max": 20,
        "description": "Build technology for payments, rewards, and risk platforms.",
        "emphasis_domains": ["java", "sql"],
        "required_skills": ["Java", "SQL"],
        "optional_skills": ["Data Analysis"],
    },
    {
        "company": "Deutsche Bank", "title": "Engineer, Technology", "sector": SECTOR_FINANCE,
        "seniority": "entry_level", "package_min": 12, "package_max": 22,
        "description": "Build platforms for global banking, markets, and risk technology.",
        "emphasis_domains": ["java", "python"],
        "required_skills": ["Java", "Python", "SQL"],
        "optional_skills": ["System Design"],
    },
    {
        "company": "Citi", "title": "Technology Analyst Program", "sector": SECTOR_FINANCE,
        "seniority": "entry_level", "package_min": 12, "package_max": 21,
        "description": "Build technology solutions across Citi's global banking businesses.",
        "emphasis_domains": ["java", "sql"],
        "required_skills": ["Java", "SQL"],
        "optional_skills": ["Python"],
    },
    {
        "company": "Barclays", "title": "Software Developer", "sector": SECTOR_FINANCE,
        "seniority": "entry_level", "package_min": 11, "package_max": 19,
        "description": "Build technology for investment banking and corporate banking platforms.",
        "emphasis_domains": ["java", "sql"],
        "required_skills": ["Java", "SQL"],
        "optional_skills": ["System Design"],
    },
]
